Repository fga-eps-mds/2019.2-Acacia, pull requests merged in 2019-10, with the labels that each got.

#101 #91 Melhorar o aspecto visual do github pages
  README.md
  _coverpage.md
  _sidebar.md
  home.css
  home.md
  img/gerenciamento/burn4.png
  img/gerenciamento/quadro4.png
  img/gerenciamento/review_quality4.jpg
  img/gerenciamento/risks3.png
  img/gerenciamento/risks4.png
  img/gerenciamento/sprint1.jpg
  img/gerenciamento/sprint2.jpg
  img/gerenciamento/sprint3.jpg
  img/gerenciamento/velocity3.png
  img/gerenciamento/velocity4.png
  img/identidade/LowFidelityPrototype.png
  img/identidade/LowFidelityPrototypeScreens_1.png
  img/identidade/LowFidelityPrototypeScreens_2.png
  img/identidade/botoes.png
  img/identidade/campos.png
  img/identidade/contraste1.png
  img/identidade/contraste2.png
  img/identidade/contraste3.png
  img/identidade/contraste4.png
  img/identidade/contraste5.png
  img/identidade/contraste6.png
  img/identidade/gitpages/gitpage_background.png
  img/identidade/gitpages/gitpage_gradient_background.png
  img/identidade/gitpages/gitpage_logo.png
  img/identidade/gitpages/gitpage_logo_corner.png
  img/identidade/gitpages/gitpage_logo_corner_2.png
  img/identidade/gitpages/gitpage_logo_icon.png
  img/identidade/navcelular.png
  img/identidade/navweb.png
  img/identidade/navweb1.png
  img/identidade/navwebsite1.png
  img/identidade/navwebsite2.png
  img/identidade/paleta.png
  img/identidade/wordmark_1.svg
  img/team/durval.jpg
  img/team/fabiola.jpg
  img/team/flavio.jpg
  img/team/hugo.jpg
  img/team/joao.jpg
  img/team/leonardo.jpg
  img/team/martha.jpg
  img/team/renato.jpg
  img/team/shayane.jpeg
  img/team/vitor.jpeg
  index.html
  package-diagram.drawio
  policies.md
  project_methodology.md
  prototype.md
  sprints/sprint_1.md
  sprints/sprint_2.md
  sprints/sprint_3.md
  sprints/sprint_4.md
  style_guide.md
Labels: documentation, enhancement, improve

#136 #121 configure enviroment variables
  .env
  .env-dev
  .env-staging
  .gitignore
  docker-compose.yml
  src/acacia/settings.py
Labels: devops

#139 #126 Atualização do canvas
  canvas.md
  img/canvas.png
Labels: product owner

#147 Documentação sprint 8
  _sidebar.md
  img/gerenciamento/agil8.png
  img/gerenciamento/burn8.png
  img/gerenciamento/conhecimento8.jpg
  img/gerenciamento/health8.png
  img/gerenciamento/retrospectiva8.png
  img/gerenciamento/review8.png
  img/gerenciamento/risks8.png
  img/gerenciamento/velocity8.png
  sprints/sprint_8.md
Labels: documentation
