Repository fga-eps-mds/2019.2-Acacia, pull requests merged in 2019-09, with the labels that each got.

#26 #15 Adiciona Descrição dos Envolvidos e dos Usuários
  docs/vision-document.md
Labels: MDS, documentation

#27 Tradução de documentos e adição de templates de issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/hist-ria-de-usu-rio.md
  .github/ISSUE_TEMPLATE/issue_template_meeting.md
  .github/ISSUE_TEMPLATE/issue_template_us.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/_sidebar.md
  docs/policies.md
Labels: EPS, documentation

#31 Atualização do termo de abertura
  docs/_sidebar.md
  docs/project_charter.md
Labels: EPS, documentation, product owner

#32 #20 Documentação das decisões sobre as tecnologias do projeto
  docs/_sidebar.md
  docs/architecture-project.md
Labels: architecture, development team, documentation

#28 Feature/15 vision document
  docs/_sidebar.md
  docs/vision-document.md
Labels: EPS, MDS, documentation

#48 Feature/24 define metrics indicators
  _sidebar.md
  docs/img/healthCheck.png
  docs/img/interface.png
  docs/img/permissions.png
  docs/img/solutionVariabilities.png
  docs/indicators_metrics.md
Labels: documentation, scrum master

#59 #39 Create canvas documentation
  _sidebar.md
  canvas.md
  img/canvas.png
Labels: documentation, product owner

#60 #37 Documento de Arquitetura
  _sidebar.md
  architecture_document.md
  architecture_techonologies.md
  code_of_conduct.md
  img/class_diagram.png
  img/diagrama_arquitetura.png
  img/diagrama_de_caso_de_uso.png
  img/diagrama_de_pacotes.jpg
  img/diagrama_entidade_relacionamento.png
  img/diagrama_entidade_relacionamento2.png
  img/diagrama_logico_de_dados.png
  img/diagrama_logico_de_dados2.png
  style_guide.md
  vision_document.md
Labels: MDS, architecture, documentation

#82 #47 Configurar integração contínua
  .github/workflows/main.yml
  docs/README.md
  requirements.txt
Labels: EPS, devops
