Repository fga-eps-mds/2019.2-Acacia, pull requests merged in 2019-11, with the labels that each got.

#151 141 relationship heroku actions deploy
  .github/workflows/deploy.yml
Labels: devops

#157 #79 configure staging enviroment
  .github/workflows/main.yml
  Dockerfile
  docker-compose.yml
  requirements.txt
  src/acacia/settings.py
  src/acacia/wait_db.py
  src/scripts/wait_for_db.py
  src/users/migrations/0001_initial.py
Labels: devops

#156 #155 Create migrations folder with initial migrations
  src/harvest/migrations/0001_initial.py
  src/harvest/migrations/__init__.py
  tox.ini
Labels: bug

#163 #160 Documentação sprint 9
  _sidebar.md
  img/gerenciamento/agil9.png
  img/gerenciamento/burn9.png
  img/gerenciamento/conhecimento9.png
  img/gerenciamento/health9.png
  img/gerenciamento/retrospectiva9.png
  img/gerenciamento/review9.jpg
  img/gerenciamento/risks9.png
  img/gerenciamento/velocity9.png
  sprints/sprint_9.md
Labels: documentation, scrum master

#197 Configuração do ambiente de produção do backend
  .enviroments/.production.deploy
  docker-compose.deploy.yml
  src/acacia/settings.py
Labels: devops

#200 Feature/168 post mortem content
  img/backend_for_frontend.jpg
  postmortem.md
Labels: documentation, feedback

#203 #179 Deploy contínuo
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/deploy.yml
  docker-compose.deploy.yml
Labels: devops
